package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.64

import (
	"context"
	"fmt"

	"github.com/graphQL_easy/graph/model"
)

// AddProduct is the resolver for the addProduct field.
func (r *mutationResolver) AddProduct(ctx context.Context, name string, price float64, description *string) (*model.Product, error) {
	id := nextID()
	product := &model.Product{
		ID:          id,
		Name:        name,
		Price:       price,
		Description: *description,
	}
	productStore[id] = product

	// Уведомляем подписчиков о новом продукте
	go func() {
		r.ProductAdded <- product
	}()

	return product, nil
}

// UpdateProduct is the resolver for the updateProduct field.
func (r *mutationResolver) UpdateProduct(ctx context.Context, id string, name *string, price *float64, description *string) (*model.Product, error) {
	product, ok := productStore[id]
	if !ok {
		return nil, fmt.Errorf("product not found")
	}

	if name != nil {
		product.Name = *name
	}
	if price != nil {
		product.Price = *price
	}
	if description != nil {
		product.Description = *description
	}

	return product, nil
}

// DeleteProduct is the resolver for the deleteProduct field.
func (r *mutationResolver) DeleteProduct(ctx context.Context, id string) (bool, error) {
	if _, ok := productStore[id]; ok {
		delete(productStore, id)
		return true, nil
	}
	return false, fmt.Errorf("product not found")
}

// Product is the resolver for the product field.
func (r *queryResolver) Product(ctx context.Context, id string) (*model.Product, error) {
	if product, ok := productStore[id]; ok {
		return product, nil
	}
	return nil, fmt.Errorf("product not found")
}

// Products is the resolver for the products field.
func (r *queryResolver) Products(ctx context.Context) ([]*model.Product, error) {
	var products []*model.Product
	for _, product := range productStore {
		products = append(products, product)
	}
	return products, nil
}

// ProductAdded is the resolver for the productAdded field.
func (r *subscriptionResolver) ProductAdded(ctx context.Context) (<-chan *model.Product, error) {
	ch := make(chan *model.Product, 1)
	r.Resolver.ProductAdded = ch
	return ch, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
